# ml_examples/Cargo.toml
[package]
name = "ml_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive_ml = { path = ".." }
csv = "1.3"
byteorder = "1.5"
flate2 = "1.0"
anyhow = "1.0"

[features]
default = ["iris", "mnist"]
iris = []
mnist = []