[package]
name = "primitive_ml"
version = "0.2.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
anyhow = "1.0"
serde_json = "1.0"
csv = "1.3"
byteorder = "1.5"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = [
    ".",
    "ml_examples",
]